apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: arrayappset
  namespace: tcbargo
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/gopaljayanthi/forjpmc.git
          revision: HEAD
          files:
          - path: arraygen/array2.yaml
      - matrix:
          generators:
          - list:
            elementsYaml: "{{ .key.namespaces | toJson }}"
          - list:
            elementsYaml: "{{ .key.components | toJson }}"
  template:
    metadata:
      name: '{{.namespace}}'
    spec:
      project: default
      syncPolicy:
        automated:
          selfHeal: true    
        syncOptions:
        - CreateNamespace=true        
      sources:
        - chart: '{{.chart}}'
          repoURL: '{{.repoUrl}}'
          targetRevision: '{{.version}}'
          helm:
            releaseName: '{{.releaseName}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
