apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: tcbargo
  finalizers:
    # Alternatively, you can use background cascading deletion
  - resources-finalizer.argocd.argoproj.io/background
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
       path: nginx-ing
       repoURL: https://github.com/gopaljayanthi/forjpmc.git
       targetRevision: HEAD
       #syncPolicy:
       #syncOptions:
       #- Replace=true
