apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: twosources
  namespace: tcbargo
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: tcbargo
  sources:
    - chart: helm-test-chart
      repoURL: 732813442182.dkr.ecr.us-east-1.amazonaws.com
      targetRevision: 0.5.0
    - repoURL: https://github.com/gopaljayanthi/forjpmc.git
      path: configmap
      targetRevision: HEAD