apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: twosourcesappset
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-twosourcesappset'
    spec:
      project: default
      sources:
       - chart: helm-test-chart
         repoURL: 732813442182.dkr.ecr.us-east-1.amazonaws.com
         targetRevision: 0.5.0
       - repoURL: https://github.com/gopaljayanthi/forjpmc.git
         path: configmap
         targetRevision: HEAD
      destination:
        server: '{{url}}'
        namespace: jpmc