apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stack-addons
  namespace: argocd
spec:
  generators:
  - git:
      files:
      - path: stack/kube-prometheus-stack/dev/config.json
      #- path: stack/kube-prometheus-stack/dev/config2.json
      repoURL: https://github.com/bitthalpatidar/forjpmc.git
      revision: master
  strategy:
    type: AllAtOnce
  syncPolicy:
    #applicationsSync: create-delete
    applicationsSync: create-update
    #applicationsSync: create-only
    #preserveResourcesOnDeletion: false
    #preserveResourcesOnDeletion: true
  template:
    metadata:
      name: in-cluster-{{name}}
    spec:
      destination:
        name: in-cluster
        namespace: '{{namespace}}'
      project: default
      sources:
      - chart: '{{chart}}'
        helm:
          parameters:
          - name: "nodeExporter.enabled"
            value: "false"
          - name: "prometheusOperator.enabled"
            value: "false"
          - name: "prometheus.enabled"
            value: "false"
          - name: "alertmanager.enabled"
            value: "false"
          releaseName: '{{name}}'
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
        retry:
          backoff:
            duration: 60s
            factor: 2
            maxDuration: 2m
          limit: 10
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
