apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stack-addons-new
  namespace: test
spec:
  generators:
  - git:
      files:
      - path: stack/kube-prometheus-stack/dev/config.json
      repoURL: https://github.com/bitthalpatidar/forjpmc.git
      revision: HEAD
  strategy:
    type: AllAtOnce
  syncPolicy:
    applicationsSync: create-delete
  template:
    metadata:
      name: in-cluster-{{name}}
    spec:
      destination:
        name: in-cluster
        namespace: '{{namespace}}'
      project: default
      sources:
      - chart: '{{chart}}'
        helm:
          releaseName: '{{name}}'
          values: |
            stack-1-prometheus-node-exporter:
              args:
                - --path.rootfs=/host/root
                - --path.udev.data=/host/root/run/udev/data
                - --web.listen-address=[$(HOST_IP)]:9101
                - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
              ports:
                http-metrics: 9101
              probes:
                readinessProbe:
                  httpGet:
                    path: /
                    port: 9101
                    scheme: HTTP
                  periodSeconds: 10
                livenessProbe:
                  httpGet:
                    path: /
                    port: 9101
                    scheme: HTTP
                  periodSeconds: 10
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
        retry:
          backoff:
            duration: 60s
            factor: 2
            maxDuration: 2m
          limit: 10
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true

# Uncomment the following section if you want to use the commented configuration

# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: stack-addons
#   namespace: argocd
# spec:
#   generators:
#   - git:
#       files:
#       - path: stack/kube-prometheus-stack/dev/config2.json
#       repoURL: https://github.com/bitthalpatidar/forjpmc.git
#       revision: HEAD
#   strategy:
#     type: AllAtOnce
#   syncPolicy:
#     applicationsSync: create-delete
#   template:
#     metadata:
#       name: in-cluster-{{name}}
#     spec:
#       destination:
#         name: in-cluster
#         namespace: '{{namespace}}'
#       project: default
#       sources:
#       - chart: '{{chart}}'
#         helm:
#           releaseName: '{{name}}'
#         repoURL: '{{repoURL}}'
#         targetRevision: '{{targetRevision}}'
#       syncPolicy:
#         automated:
#           allowEmpty: true
#           prune: true
#         retry:
#           backoff:
#             duration: 60s
#             factor: 2
#             maxDuration: 2m
#           limit: 10
#         syncOptions:
#         - CreateNamespace=true
#         - ServerSideApply=true
