apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appsetwithpvc
spec:
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: cluster
              operator: In
              values:
                - in-cluster
          maxUpdate: 100%
        - matchExpressions:
            - key: cluster
              operator: In
              values:
                - isdmkp
          maxUpdate: 100%
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
      - cluster: isdmkp
        url: https://146.148.79.161
  template:
    metadata:
      name: '{{cluster}}-appwithcm'
    spec:
      project: default
      source:
        repoURL: https://github.com/gopaljayanthi/forjpmc.git
        targetRevision: HEAD
        path: configmap
      destination:
        server: '{{url}}'
        namespace: jpmc
      syncPolicy:
        automated: {}
