# Source: genesis/templates/addons-appset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appsettest
  namespace: test
spec:
  generators:
    - git:
        repoURL: https://github.com/bitthalpatidar/forjpmc.git
        revision: master
        files:
        - path: "sync-wave/**/config.json"
  strategy: 
    type: RollingSync
    rollingSync: 
      steps: 
        - matchExpressions:
            - key: syncWave
              operator: In
              values: 
                - zero
          maxUpdate: 100%
        - matchExpressions:
            - key: syncWave
              operator: In
              values: 
                - one
          maxUpdate: 100%
        - matchExpressions:
            - key: syncWave
              operator: In
              values: 
                - two
          maxUpdate: 100%
        - matchExpressions:
            - key: syncWave
              operator: In
              values: 
                - three
          maxUpdate: 100%
        - matchExpressions:
            - key: syncWave
              operator: In
              values: 
                - four
          maxUpdate: 100%
        - matchExpressions:
            - key: syncWave
              operator: In
              values: 
                - five
          maxUpdate: 100%
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  template:
    metadata:
      name: 'appsettest-{{name}}'
      labels: 
        syncWave: '{{syncwave}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncwave}}'
    spec:
      project: default
      sources:
        - repoURL: '{{repoURL}}'
          targetRevision: '{{targetRevision}}'
          chart: '{{chart}}'
          ref: '{{ref}}'
        - repoURL: https://github.com/bitthalpatidar/forjpmc.git
          targetRevision: master
          path: pod-cm
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
