apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appsettest
  namespace: test
spec:
  generators:
    - git:
        repoURL: https://github.com/bitthalpatidar/forjpmc.git
        revision: master
        files:
        - path: "sync-wave/wave-one/config.json"
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: syncWave
              operator: In
              values:
                - one
          maxUpdate: 100%
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  template:
    metadata:
      name: 'appsettest-{{name}}'
      labels:
        syncWave: '{{syncWave}}'
    spec:
      project: default
      source:
        # - repoURL: '{{repoURL}}'
        #   targetRevision: '{{targetRevision}}'
        #   path: '{{path}}'
          repoURL: https://github.com/bitthalpatidar/forjpmc.git
          targetRevision: master
          path: pod-cm
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
