apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jpmctest
  labels:
    app: jpmctest
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: pv94
