name: Create Branch with Application Name

on:
  repository_dispatch:
    types: [argocd-event]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - name: Get current timestamp
      id: timestamp
      run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV
    - name: Get commit ID
      id: commit
      run: echo "COMMIT_ID=${GITHUB_SHA::7}" >> $GITHUB_ENV
    - name: Create new branch with timestamp
      run: |
        git fetch origin master
        git checkout master
        git checkout -b mainchart-qa--${{ env.COMMIT_ID }}-${{ env.TIMESTAMP }}
        git push origin mainchart-qa--${{ env.COMMIT_ID }}-${{ env.TIMESTAMP }}
